### PR TITLE
alert component

### PR DESCRIPTION
**Pull request by aamir74**
created different styles of alerts.

### CODE REVIEW

**Comment by SaiArunesh** [comment]
Below 220px text overflows out of alert container

**Review by SaiArunesh — CHANGES_REQUESTED** [review]
below 220px text overflows out of container. warning , info, success classes may be updated as alert-warning alert-info to make them specific to alert component's bg coloring. Otherwise bg-danger, bg-warning also sounds specific enough,

**Review by mohammed-sas — APPROVED** [review]
your code is good to merge

**Comment by aamir74** [comment]
I've committed the changes arunesh. 

>

**Comment by aamir74** [comment]
> below 220px text overflows out of container. warning , info, success classes may be updated as alert-warning alert-info to make them specific to alert component's bg coloring. Otherwise bg-danger, bg-warning also sounds specific enough,

**Comment by aamir74** [comment]
> below 220px text overflows out of container. warning , info, success classes may be updated as alert-warning alert-info to make them specific to alert component's bg coloring. Otherwise bg-danger, bg-warning also sounds specific enough,

I've made the changes and committed and I've read about responsiveness found that screen sizes below 350px are very rare so ignored.

**Comment by aamir74** [comment]
> > below 220px text overflows out of container. warning , info, success classes may be updated as alert-warning alert-info to make them specific to alert component's bg coloring. Otherwise bg-danger, bg-warning also sounds specific enough,

Hey arunesh, I've done the suggested changes can you approve now

**Comment by aamir74** [comment]
Hey arunesh, I've done the suggested changes can you approve now

**Review by SaiArunesh — APPROVED** [review]

**Pull request merged**
